import React from 'react'

function Tips() {
  return (
    <div>
        <button>Tips</button>
        <br/>
      MOSKOW ADALAH KOTA TERBESAR DIRUSIA, TOTAL PENDUDUK MOSKOW SAAT INI<br/> 
      DIPERKIRAKAN LEBIH DARI 1 ORANG. HIDUP DI KOTA BESAR TENTUNYA BUKAN HAL <br/>
      YANG MUDAH TERLEBIH LAGI KALAU BUKAN DI NEGARA SENDIRI. BERIKUT TIPS <br/>
      TIPS DARI PERMOS UNTUK TINGGAL DI MOSKOW SEBAGAI PELAJAR:<br/><br/>

MENGIKUTI KEGIATAN PERMOS<br/>
SELALU JAGA SILAHTURAHMI DENGAN TEMAN TEMAN LAIN YANG BERKULIAH DI MOSKOW<br/>
DLL
    </div>
  )
}

export default Tips
